[project]
name = "pratyush-dbt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Pratyush kumar", email = "pratyushdubey006@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "dbt-core>=1.12.3",
    "dbt-databricks>=1.12.5",
]

[project.scripts]
pratyush-dbt = "pratyush_dbt:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
